apiVersion: v1
kind: Service
metadata:
  name: {{ include "viz.fullname" . }}
  labels:
    {{- include "viz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    {{- include "viz.selectorLabels" . | nindent 4 }}
