apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "feeder.fullname" . }}
  labels:
    {{- include "feeder.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "feeder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "feeder.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: feeder
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NATS_URL
              value: {{ .Values.natsUrl | quote }}
